# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: BitWorking
title_image: https://bitworking.org/images/newlogo.png
email: joe@bitworking.org
description: > # this means to ignore newlines until "baseurl:"
  Joe Gregorio - REST, Web, Python, Go, APIs, Dad, Husband, Maker, or any linear combination of such. Googler.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bitworking.org" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:categories/:year/:month/:title
twitter_username: bitworking
github_username:  jcgregorio

disqus:
  shortname: bitworking-1

google_analytics: UA-1974123-1

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-last-modified-at
feed:
  path: /news/feed/index.atom
exclude:
  - Gemfile
  - Gemfile.lock
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      categories: "news"
      author: "Joe Gregorio"
