#!/bin/bash
APPNAME=userve
DESCRIPTION="userve."
SYSTEMD="${APPNAME}.service"
DEPENDS=git

# Copy files into the right locations in ${ROOT}.
copy_release_files()
{
INSTALL="sudo install -D --verbose --backup=none --group=root --owner=root"
${INSTALL} --mode=755 -T ${GOPATH}/bin/userve  ${ROOT}/usr/local/bin/userve
${INSTALL} --mode=644 -T ${APPNAME}.service    ${ROOT}/etc/systemd/system/${APPNAME}.service
}

source release.sh
