#!/bin/bash

filename=./_posts/$(date +%Y-%m-%d)-`echo -ne $@ | tr '[:upper:]' '[:lower:]' | tr '[:space:]' '-'`.md
cat >$filename <<EOL
---
layout: post
title: $@
---


<a href="https://brid.gy/publish/twitter"></a>
EOL

vim $filename
