#!/bin/bash

set -e -x

JEKYLL_ENV=production bundle exec jekyll build
git add --all
git commit -m "publish"
git push
#ssh jcgregorio@bitworking.org 'cd ~/blog; git pull'
firebase deploy
xmlstarlet sel -t -m "//_:entry/_:link[@rel='alternate']/@href" -v . -n ./_site/news/feed/index.atom | head -n 1 | xargs -L 1 webmention-cli -selector .post-content
