#!/bin/bash

set -e -x

hugo -D
firebase deploy
xmlstarlet sel -t -m "//_:entry/_:link[@rel='alternate']/@href" -v . -n ./_site/news/feed/index.atom | head -n 1 | xargs -L 1 webmention-cli -selector .post-content
